### ISSUE TITLE
geowave cli tools don't recognize bigtable type

### ISSUE THREAD

**Issue by dsacharny** [ngageoint/geowave#1067]
I was hoping to test out geowave with my bigtable instance but I get this error:

> geowave config addstore -t bigtable
Usage: geowave config addstore [options] <name>
  Options:
    -d, --default
       Make this the default store in all operations
    -t, --type
       The type of store, such as accumulo, memory, etc
       Default: bigtable

**Error: Unknown datastore type: bigtable**

Looking through the code it does seem like bigtable should be a recognized store type. I compiled this from the master branch. Perhaps I missed a configuration item?

**Comment by rfecher** [comment]
nope, you didn't miss configure anything.  we weren't packaging bigtable in our default package for 0.9.3 because we wanted to ensure full functionality. We were going to package it in 0.9.4, thanks for pinging us.  Its in the default packaging on master now.

If I recall correctly there seemed to be some issues with raster data in BigTable back in December, at least the emulator, regarding row size limitations.  We hit this ticket (#861) after our 0.9.3 release with this commit (https://github.com/ngageoint/geowave/commit/66949d35d9dc2cba1360ae545f423b148f8b9faf) and can feel more confident in full functionality so it is now included in our default deployment and packaging for our 0.9.4 release next month.  Basically we annotate all of our integration tests (ITs are in test) with the datastore type, and every commit is run in travis CI with for example BigTable as an element of the matrix to ensure we maintain full functionality with each store (https://travis-ci.org/ngageoint/geowave/builds/216453375).  In this case tests against BigTable is run using Google's BigTable Emulator, but it should give us reasonable confidence that every capability annotated with BigTable within our tests works and will be maintained in the future. I only get into that detail because it seems like you're able to get deeper into the code considering you mention already looking through it, so you can look at the ITs and see exactly what sorts of functionality is being verified within BigTable.  We use SPI for discovery of datastores at runtime and the BigTable datastore was simply not on the classpath before now.

But you can try it now.  `mvn package -am -pl deploy -DskipTests -Dfindbugs.skip -P geowave-tools-singlejar` from the root directory is my quick way to build the commandline tools as a single jar and the only other thing required on that is going to be a <name> that you give it.  Then for other commands like ingest you'd reuse that <name>. 
 So for example to ingest a local shapefile (or any other file type supported by geotools) you'd config your datastore, then `geowave config -t spatial <my index name>` then `geowave ingest localToGw <path to file> <datastorename> <index name> -f geotools-vector`.  Good luck!

**Comment by syncharny** [comment]
Wow. @rfecher Thank you so much
