### ISSUE TITLE
implement geowavefileoutput format for high-speed ingest

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#157]
analogue to accumulofileoutputformat

**Comment by keith-turner** [comment]
Did something similar to this w/ [Fluo][1].  Fluo has a specialized data format that it stores in Accumulo like Geowave.   [FluoFileOutputFormat][2] leverages/wraps code from AccumuloFileOutputFormat.  Later while looking into wrapping AccumuloOutputFormat, I decided it would be easier to write something that simply produces mutations instead.   [MutationBuilder][3] does this and was much easier to write than something that wraps AccumuloOutputFormat.  I have thought about scrapping FluoFileOutputFormat and instead writing a simple class that produces Accumulo Keys.  A user could use this class to produces Keys that are written using AccumuloFileOutputFormat.   

[1]: https://github.com/fluo-io/fluo
[2]: https://github.com/fluo-io/fluo/blob/fc80d097c6df4b9e26ebd0c2bef38d8e2dc447c6/modules/mapreduce/src/main/java/io/fluo/mapreduce/FluoFileOutputFormat.java
[3]: https://github.com/fluo-io/fluo/blob/fc80d097c6df4b9e26ebd0c2bef38d8e2dc447c6/modules/mapreduce/src/main/java/io/fluo/mapreduce/MutationBuilder.java

**Comment by rfecher** [comment]
Thanks Keith,  wrapping the AccumuloFileOutputFormat's record writer is probably the simplest approach for us to follow too.

**Comment by dcy2003** [comment]
I initially started down the path of implementing a `GeowaveFileOutputFormat` (that wraps `AccumuloFileOutputFormat`) as specified in the details of this ticket.  After banging my head against this approach for a few days, I am encountering some of the same challenges that I believe Keith was alluding to, and I think the approach he is recommending makes more sense.  

Here is my attempt to shed a little more light on the issue and propose an alternative approach:

Per the documentation, when leveraging `AccumuloFileOutputFormat` to write output in the Accumulo data file format, 
> “care should be taken to write only sorted data (sorted by org.apache.accumulo.core.data.Key), as this is an important requirement of Accumulo data files.”

In attempting to leverage `AccumuloFileOutputFormat` within a wrapping `GeowaveFileOutputFormat`, we must delegate to the `write()` method of AccumuloFileOutputFormat’s `RecordWriter`, which expects [`org.apache.accumulo.core.data.Key`, `org.apache.accumulo.data.Value`].  If we attempt to construct these Keys and Values within our `GeowaveFileOutputFormat` from the output of our Reducer, **the Keys we construct will not meet the requirement of being properly sorted.**

To achieve our goal of high-speed ingest, what I think we could do instead is:

1. Implement a `GeowaveKeyBuilder` (name negotiable) that would be used within our MR job to produce Accumulo Keys in the proper Geowave format 
2. Configure the output format of our MapReduce job to use `AccumuloFileOutputFormat` directly, since we will be handing it keys in a format that it expects
3. We can then perform bulk ingest of this output easily via the method outlined here https://accumulo.apache.org/1.6/accumulo_user_manual.html#_bulk_ingest

Thoughts?  Feedback?  Alternative suggestions?  Happy to discuss further… I am admittedly still playing catchup and may be overlooking something obvious…

**Comment by keith-turner** [comment]
> Thoughts? Feedback? Alternative suggestions? Happy to discuss further… I am admittedly still playing catchup and may be overlooking something obvious…

You reminded me that I meant to open a Fluo issue for this.  I am curious to see how this approach works out, if there are any road blocks you will run into.  Are you going to try to create an end to geowave ingest example that utilizes this proposed approach?  Thats one way to shake out any potential roadblocks.

**Comment by rfecher** [comment]
Yep, I'm sorry, I didn't dig deep enough when I made the ticket.  And in re-reading the comments now, I totally missed the point initially that @keith-turner was alluding to.  By just wrapping the AccumuloFileOutputFormat, we can expose a *technically* valid outputformat that can work with our native data types (intuitive "geo" objects rather than key/value) but we wouldn't be able to guarantee sort order as @dcy2003 pointed out.  I think you're on the right track, to instead completely re-use AccumuloFileOutputFormat as is, considering aggregating a mapreduce job by accumulo Key is really the way to ensure sort order.

There may be a piece of this that is still a bit more like a core re-usable component rather than purely example - @dcy2003, you may want to look at how we provide some basic building blocks in [this package] (https://github.com/ngageoint/geowave/tree/master/geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/mapreduce) or how we use that to provide a default dedupe mapreduce job [here] (https://github.com/ngageoint/geowave/blob/master/geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/mapreduce/dedupe/GeoWaveDedupeJobRunner.java).  Just a thought...if it doesn't seem like there's anything generic enough here to provide in the core, I think an end-to-end ingest example would be good at least.

**Comment by keith-turner** [comment]
FYI I made a PR for Fluo for this fluo-io/fluo#487

**Comment by dcy2003** [comment]
Thanks @keith-turner, I will take a look.  I have this coming on our end too.  Working on an Integration Test right now, should have a PR submitted this week.
