### ISSUE TITLE
Bounding box stats are not stored as EPSG:4326

### ISSUE THREAD

**Issue by jwomeara** [ngageoint/geowave#305]
Should they be?

I ran into this issue when ingesting a shapefile which used UTM coordinates.  The bounds that are  maintained in BoundingBoxDataStatistics are in UTM coordinates and not lat/lon.  This caused a bit of grief for me when trying to ingest some of the mapnik-provided shapefiles.  I think it would be preferable if the coordinate systems used to store data and statistics matched.  It just seems weird to always return coordinates as lat/lon when doing a query, but returning native coordinates when hitting up statistics.

**Comment by chrisbennight** [comment]
I think they have to be; right now geometries are the only portion of a feature that we normalize the actual value of (as persisted), and we probably (as a result of this) derive the obligation to do that for anything which touches geometry.

Question would be - is it worth it (can we) relocate the statistics emission to after the conversion has taken place, or do we need to do a separate re-projects for geometries in statistics.   (I don't think we delegate it to the statistics/mergeable implementation, since that runs in iterator scope as well - and at that point would be extraneous/dead code)

**Comment by jwomeara** [comment]
Could we just pass the reprojected type to the stats manager when the feature data adapter is created?  Then when the stats manager creates the Feature Bounding Box Stats it can pass the reprojected type.

**Comment by jwomeara** [comment]
Somebody want to check out my fix?  #308
