### ISSUE TITLE
Implement a WholeFeatureDataAdapter

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#380]
Provide an option to store a whole simplefeature in the value of a single row.  We think it would make sense to encode this using Avro.  Currently, FeatureDataAdapter stores each attribute individually in the column family, which will give the user the opportunity to provide visibility per attribute.  However, if separate visibility for each attribute is not necessary, it is likely to be more efficient to store each feature completely in a single column family and the whole feature in the value.

**Comment by rwgdrummer** [comment]
The adapter encoding provides a set of PersistentValues.   These values are used to populate alternate indices.   As it stands now, statistics use the whole object rather than the itemized objects in the persistent data set.   As long as the adapter provides the set of persistent values for alternate indices, a single encoding for the entire feature should not have significant issues.   

Avro considerations include one schema per each Feature Data Adapter (per type) vs. one Avro definition for all Feature Types (a generalized Avro schema).

**Comment by rwgdrummer** [comment]
Based on the discussion today, Avro is likely to be associated with each feature type, thus, each adapter instance.  The adapter would need to encode/decode that schema as part of its binary image stored in the adapter store.  Recall the adapter is deserialized from the adapter store in iterators  to decode column data.  In this case, the column data is the Avro image of a simple feature.

I requested the tool that constructs an Avro schema from a simple feature be made available separately to be used in #353
