### ISSUE TITLE
Error in log file re: missing zookeeper server params

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#439]
This looks to me to be an issue with the logic on validating if a plugin can process data (at least in the integration test context)

Things looked okay here:
https://travis-ci.org/ngageoint/geowave/jobs/68079678
(Merge #434 - Asciidoc changes )

Next merge on master was this:
https://travis-ci.org/ngageoint/geowave/jobs/68079920
(Merge #430 - Content Data Store )

If you search for "missing" in the second job
(example: https://travis-ci.org/ngageoint/geowave/jobs/68079920#L3345 )
 you will note we have lots of errors of the form:

```
27 Jun 15:58:16 ERROR [plugin.GeoWaveGTDataStoreFactory] - Invalid parameters
mil.nga.giat.geowave.adapter.vector.plugin.GeoWavePluginException: Accumulo Plugin: Missing zookeeper servers param
	at mil.nga.giat.geowave.adapter.vector.plugin.GeoWavePluginConfig.<init>(GeoWavePluginConfig.java:150)
	at mil.nga.giat.geowave.adapter.vector.plugin.GeoWaveGTDataStoreFactory.canProcess(GeoWaveGTDataStoreFactory.java:132)
	at org.geotools.data.DataAccessFinder.getDataStore(DataAccessFinder.java:109)
	at org.geotools.data.DataStoreFinder.getDataStore(DataStoreFinder.java:89)
	at mil.nga.giat.geowave.format.geotools.vector.GeoToolsVectorDataStoreIngestPlugin.supportsFile(GeoToolsVectorDataStoreIngestPlugin.java:83)
	at mil.nga.giat.geowave.core.ingest.local.LocalPluginFileVisitor$PluginVisitor.supportsFile(LocalPluginFileVisitor.java:74)
(...)
```

Specifically It looks like this line https://github.com/ngageoint/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveGTDataStoreFactory.java#L132
is responsible.   

in the integration tests this map only has  one value - "url":"file:/path/to/hail.shp"

Doesn't look like it will break general functionality (Seems to be an issue with that code path only passing url parameter and not the rest) - but still a gotcha.  Might be a working as intended (though don't think so) - but in that case we at a minimum need a different log/error message.

@rfecher @dcy2003

**Comment by dcy2003** [comment]
Thanks for pointing this out.  When GeoTools is attempting to determine the appropriate Data Store implementation, it iterates available Data Stores and calls canProcess() on each (see https://github.com/geotools/geotools/blob/aa0d0346e4bb4a5a2055559c22d2b12ded7cbd20/modules/library/main/src/main/java/org/geotools/data/DataAccessFinder.java#L109).  The logic of the existing canProcess() method should be correct, the issue was simply the unnecessary logging statement (https://github.com/ngageoint/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveGTDataStoreFactory.java#L137) polluting the logs in instances where there was no match and canProcess() is about to correctly return false.
