### ISSUE TITLE
CORS does not work in Jetty due to jetty-servlets.jar missing

### ISSUE THREAD

**Issue by ector8301** [ngageoint/geowave#678]
You can find the jar at:
http://search.maven.org/#search%7Cgav%7C1%7Cg:%22org.eclipse.jetty%22%20AND%20a:%22jetty-servlets%22

Please add it to your repository.

**Comment by dcy2003** [comment]
@ector8301 we are closing this issue based on our discussion yesterday.  You know where to find us if you would like to discuss further after speaking with your teammates.

**Comment by rfecher** [comment]
this was closed because it is outside of the scope of GeoWave.  We do have an rpm that installs the GeoServer standalone with GeoWave support, but the GeoWave support in GeoServer is just an additional jar in GeoServer's WEB-INF/lib (following these instructions for building the jar: http://ngageoint.github.io/geowave/documentation.html#geoserver-2).  More specifically, this is an issue with the version of Jetty that GeoServer 2.8.2 standalone uses, and GeoServer 2.9+ seems to have resolved it (https://osgeo-org.atlassian.net/browse/GEOS-6605).  Alternatively, one could download the geoserver WAR to be used in their container of choice (the latest version of Tomcat or Jetty should suffice): http://sourceforge.net/projects/geoserver/files/GeoServer/2.8.2/geoserver-2.8.2-war.zip
Then its a matter of following the geowave documentation to build the GeoWave GeoServer plugin from GeoWave source, or to simply download a compressed tarball of a released version of GeoWave from here.  The tarball has "geowave-geoserver.jar" in it which can go in the WEB-INF/lib folder of any deployed GeoServer 2.8.2 (for example for GeoWave 0.9.2.1 here's what you'd want: http://s3.amazonaws.com/geowave-rpms/release/TARBALL/geowave-apache-0.9.2.1-f4d8740.tar.gz).

**Comment by jnewmoyer** [comment]
To enable CORS, copy the jetty-servlets.jar to geoserver/WEB-INF/lib (you can copy it right out of the server/lib) which puts it into the webapp scope.

**Comment by rfecher** [comment]
thanks, in reading https://osgeo-org.atlassian.net/browse/GEOS-6605 it seems the jetty-servlets.jar is not yet part of the geoserver standalone distro but may be coming soon?

**Comment by jnewmoyer** [comment]
It looks like they updated the Jetty that comes bundled with the standalone distro, but you would still have to copy jetty-servlets.jar to the geoserver/WEB-INF/lib. I use the GeoServer war distro with Jetty 9 and this is what I do in my packaging scripts.

**Comment by jnewmoyer** [comment]
Also, you need the jetty-util.jar
