### ISSUE TITLE
Parameters for Analytics Need Clearer Documentation

### ISSUE THREAD

**Issue by ScottEvil** [ngageoint/geowave#701]
Under the Analytics section in the documentation there is a single table of parameters that isn't complete and also contains params for all of the analytics. The documentation needs to be broken out so that there are clear sets of params for each analytic. Most likely we'll need a table for each set of analytic parameters.

**Comment by datasedai** [comment]
I think we should try to match the arguments of Python-like libraries as much as possible, and hide arguments for parameters that aren't typically set.  Here are some links that I pulled up for some of the similar operations in Python.

http://scikit-learn.org/stable/modules/generated/sklearn.cluster.dbscan.html

http://docs.scipy.org/doc/scipy/reference/cluster.vq.html

http://scikit-learn.org/stable/modules/neighbors.html

http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.gaussian_kde.html

**Comment by rfecher** [comment]
I think we agree simplification is important and think this is a good way to go @datasedai

**Comment by rwgdrummer** [comment]
I can work with you on that.  Let me schedule a time next week to come out their to go over the parameters.  

RE: DESCAN:

A write up for DBScan is : https://github.com/ngageoint/geowave/wiki/DBScan
Since this DBScan is designed to scale and pull from GeoWave, it has more parameters (most which are common among ALL the analytics).

The require parameters for DB Scan algorithms are max distance ("-pmd" called eps in scikit) and minimum cluster size ("cms" called min_samples in scikit).  

In all analytics:
A hdfs_base directory is needed for the interim work.
The input store parameters are needed.
Ideally, a query and query option parameters are also supplied to select the adapter and data set....but not required.

The min and max input splits (emn and emx) are recommend.  The default is too small.  It is better to increase both of them for large data sets.  For example, a minimum of 100 or even a thousand is ok.  
http://www.dummies.com/how-to/content/input-splits-in-hadoops-mapreduce.html

But, I do not recommend hiding anything.  Depending on cluster sizes and data size, every parameter has value. We just need to articulate how to use them.

**Comment by rwgdrummer** [comment]
The distance function for DBScan is , by default, FeatureGeometryDistanceFn.   Unlike KMeans, which measures distance from the centroid, DBScan measures shortest distance of two geometries from the perimeter.

**Comment by rwgdrummer** [comment]
-ifc --inputFormatClass and -iip --inputHDFSPath are used to override the default GeoWaveInputFormat to pull data from a sequence file.
Example:
-ifc  mil.nga.giat.geowave.analytic.mapreduce.SequenceFileInputFormatConfiguration -iip "mydatadirinHDFS"
