### ISSUE TITLE
Investigate use of enabling/disable tables for admin operations within BasicHBaseOperations

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#858]
It seems like we want to avoid this, but need to understand our options.

**Comment by blastarr** [comment]
Start here: https://github.com/ngageoint/geowave/blob/master/extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/io/HBaseWriter.java#L92

**Comment by blastarr** [comment]
It doesn't look like there's a way to avoid the blocking enable/disable of tables when we update the schema w/ new column families on ingest.  
  
However, I was able to get about a 70% improvement on ingest time by caching database info instead of doing the DB lookup on each and every row ingest.  
  
[ingestperf.xlsx](https://github.com/ngageoint/geowave/files/376652/ingestperf.xlsx)

**Comment by blastarr** [comment]
Comparing baseline HBase ingest with this branch's modifications shows a consistent 4x improvement using various amounts of GDELT data.
