### ISSUE TITLE
Investigate the performance implication in use of coprocessors for DistributableQueryFilter

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#862]

**Comment by blastarr** [comment]
Endpoint coprocessor call goes here:  
   
https://github.com/ngageoint/geowave/blob/master/extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/query/HBaseConstraintsQuery.java#L133

**Comment by blastarr** [comment]
Coprocessors are essentially simple RPC calls to each region server using protobuf for serialization (not like the Accumulo 'iterator') - so they are only useful for aggregation. However, since it was necessary to wrap our DistributableQueryFilter in an HBase 'Filter' impl, we can make use of that class directly in an HBase filter list and apply it to our scanner.  
  
So the 'coprocessor' per se was not the solution for generic use of DistributableQueryFilter in HBase, but the HBase Filter wrapper turned out to be the right answer.

**Comment by blastarr** [comment]
Using custom Coprocessor classes as well as custom Filter classes requires deployment of a custom jar to each region server.  
  
In the HBase project, I've added the 'hbase-singlejar' profile which generates the necessary jar for hbase deployment. We can't just use the 'geowave-tools' uber-jar, because it's far too big to survive the dynamic distribution to the nodes.  
  
The best (and possibly only) way to accomplish deployment of a custom jar to the HBase classpath on each node in an EMR cluster is to make use of the 'hbase.dynamic.jars.dir' property, and point it at an HDFS location on the master node. Luckily, this property already defaults to the value of 'hbase.rootdir'/lib, and EMR deploys HBase w/ this value set to hdfs://<master_node_ip>:8020/user/hbase.  
  
So all we have to do in our cluster bootstrap script is copy the jar on the master node to the indicated HDFS URL, and HBase will find the custom classes (for both Coprocessors and Filters) using its DynamicClassLoader.

**Comment by blastarr** [comment]
In order to allow GeoWave users to deploy on HBase without dealing w/ custom classes, I've added some store options that allow queries to run without coprocessors or custom filters (basically just using client-only filters):  
  
- enableCoprocessors (boolean): if true, will use a coprocessor for aggregations. This will require deployment of the geowave-hbase.jar (see previous comment), and registration of the aggregation  coprocessor in one of three ways:  
  
1. Register globally in the hbase-site.xml properties, like this:  
    <property>  
        <name>hbase.coprocessor.region.classes</name>  
        <value>mil.nga.giat.geowave.datastore.hbase.query.AggregationEndpoint</value>  
    </property>  
  
2. Register on each table that will use it via the HBase shell:  
  > hbase shell  
  > alter 'SPATIAL_IDX', METHOD => 'table_att', 'coprocessor'=>'hdfs://ip-10-0-0-81:8020/user/hbase/lib/geowave-hbase.jar|mil.nga.giat.geowave.datastore.hbase.query.AggregationEndpoint|1001'  
  
3. Let GeoWave verify and register (if necessary), whenever a coprocessor is called. In this case, we must use two more geowave store options:  
  - verifyCoprocessors = true. When an aggregation query is called, this will check the table for coprocessor registration. If not, it will use the HBase API to register it on the table. In order for this to work, we need to know where the custom jar is located in HDFS, using this option:  
  - coprocessorJar=hdfs://ip-10-0-0-81:8020/user/hbase/lib/geowave-hbase.jar  
  
Also, for custom filters, we can enable their use by setting the store option:  
- enableCustomFilters=true. This simply requires the presence of the custom jar, using the means described in the previous comment (there is no 'registration' of custom filters).
